obj-$(CONFIG_INPUTHUB_20) += ps_para_table_ams_tmd2755.o
obj-$(CONFIG_INPUTHUB_20) += ps_para_table_emin_mn78911.o
obj-$(CONFIG_INPUTHUB_20) += ps_para_table_stk_stk33562.o
obj-$(CONFIG_INPUTHUB_20) += ps_para_table_hx_hx32062se.o
obj-$(CONFIG_INPUTHUB_20) += ps_para_table_sip_sip3510.o
